[simulation]
exercise = 1
dtSimulation = 0.001
outputInterval = 10
verbose = false
tableWidth = 224
tableHeight = 112
whiteBallCoords = [ 56.0, 56.0,]
whiteBallVx = 100.0
ballMass = 165
ballDiameter = 5.7
integration = "gear"
generateFixed = false

[files]
staticInput = "./static.txt"
output = "./out/output.txt"

[benchmarks]
whiteBallYRange = [ 42.0, 56.0,]
initialPositions = 20
rounds = 5
