[simulation]
exercise = 2
dtSimulation = 0.001 # s
outputInterval = 5 # time steps interval
verbose = false
tableWidth = 224
tableHeight = 112
whiteBallCoords = [ 56.0, 56.0,]
whiteBallVx = 150.0
ballMass = 165
ballDiameter = 5.7

[files]
staticInput = "./static.txt"
output = "./out/output.txt"